# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
    -   id: check-yaml
    -   id: check-docstring-first
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.29.0
    hooks:
    -   id: yapf
        args: [--style=google, --in-place]

-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.4.4
    hooks:
    -   id: pylint
        args: [--output-format=colorized]
