# See https://pre-commit.com for more information

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
    -   id: check-yaml
    -   id: check-docstring-first
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        args: [--style=google, --in-place]

-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.0
    hooks:
    -   id: pylint
        args: [--output-format=colorized]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
