{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user.readonly": {
          "description": "See info about users on your domain"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "basePath": "",
  "baseUrl": "https://cloudidentityscim.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Cloud Identity SCIM",
  "description": "cloudidentityscim.googleapis.com API.",
  "discoveryVersion": "v1",
  "documentationLink": "https://cloud.google.com/identity/",
  "fullyEncodeReservedExpansion": true,
  "id": "cloudidentityscim:v1",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://cloudidentityscim.mtls.googleapis.com/",
  "name": "cloudidentityscim",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "customers": {
      "resources": {
        "v2": {
          "resources": {
            "Groups": {
              "methods": {
                "create": {
                  "description": "Creates a Group.",
                  "flatPath": "v1/customers/{customerId}/v2/Groups",
                  "httpMethod": "POST",
                  "id": "cloudidentityscim.customers.v2.Groups.create",
                  "path": "v1/customers/{customerId}/v2/Groups",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "delete": {
                  "description": "Deletes a Group.",
                  "flatPath": "v1/customers/{customerId}/v2/Groups/{groupId}",
                  "httpMethod": "DELETE",
                  "id": "cloudidentityscim.customers.v2.Groups.delete",
                  "path": "v1/customers/{customerId}/v2/Groups/{groupId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "get": {
                  "description": "Retrieves a Group.",
                  "flatPath": "v1/customers/{customerId}/v2/Groups/{groupId}",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.Groups.get",
                  "path": "v1/customers/{customerId}/v2/Groups/{groupId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "description": "Retrieves a list of Groups. * Requests must specify a filter. Requests without a `filter` parameter return a `tooMany` error. * The `filter` parameter only supports equality on `displayName` (for example, `displayName eq \"Group Name\"`) or `externalId` (for example, `externalId eq \"ddaafa46e2b6\"`). * Sub-string matches (`co`, `sw`, `ew`), logical operators (`and`, `or`), and complex value filters are not supported. * Pagination is not supported. If there are [...]",
                  "flatPath": "v1/customers/{customerId}/v2/Groups",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.Groups.list",
                  "path": "v1/customers/{customerId}/v2/Groups",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "patch": {
                  "description": "Updates a Group using SCIM patch semantics. * A maximum of **2** operations is supported per Group patch request. * A maximum of **1** member addition or removal is supported per Group patch request. * Supported operations and attributes: * `add`: Supported for `displayName`, `description`, `members`, and `externalId`. * `remove`: Supported for `description` and `members` (requires a value filter using the `eq` operator on the `value` sub-attribute, for example,[...]",
                  "flatPath": "v1/customers/{customerId}/v2/Groups/{groupId}",
                  "httpMethod": "PATCH",
                  "id": "cloudidentityscim.customers.v2.Groups.patch",
                  "path": "v1/customers/{customerId}/v2/Groups/{groupId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            },
            "ResourceTypes": {
              "methods": {
                "get": {
                  "description": "Retrieves a specific resource type.",
                  "flatPath": "v1/customers/{customerId}/v2/ResourceTypes/{resourceTypeId}",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.ResourceTypes.get",
                  "path": "v1/customers/{customerId}/v2/ResourceTypes/{resourceTypeId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user",
                    "https://www.googleapis.com/auth/admin.directory.user.readonly",
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "description": "Retrieves all resource types.",
                  "flatPath": "v1/customers/{customerId}/v2/ResourceTypes",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.ResourceTypes.list",
                  "path": "v1/customers/{customerId}/v2/ResourceTypes",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user",
                    "https://www.googleapis.com/auth/admin.directory.user.readonly",
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            },
            "Schemas": {
              "methods": {
                "get": {
                  "description": "Retrieves a Schema.",
                  "flatPath": "v1/customers/{customerId}/v2/Schemas/{schemaId}",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.Schemas.get",
                  "path": "v1/customers/{customerId}/v2/Schemas/{schemaId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user",
                    "https://www.googleapis.com/auth/admin.directory.user.readonly",
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "description": "Retrieves all Schemas.",
                  "flatPath": "v1/customers/{customerId}/v2/Schemas",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.Schemas.list",
                  "path": "v1/customers/{customerId}/v2/Schemas",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user",
                    "https://www.googleapis.com/auth/admin.directory.user.readonly",
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            },
            "ServiceProviderConfig": {
              "methods": {
                "get": {
                  "description": "Retrieves the Service Provider Configuration.",
                  "flatPath": "v1/customers/{customerId}/v2/ServiceProviderConfig",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.ServiceProviderConfig.get",
                  "path": "v1/customers/{customerId}/v2/ServiceProviderConfig",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user",
                    "https://www.googleapis.com/auth/admin.directory.user.readonly",
                    "https://www.googleapis.com/auth/cloud-identity.groups",
                    "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            },
            "Users": {
              "methods": {
                "create": {
                  "description": "Creates a User. * When creating a user that conflicts with an existing unmanaged consumer account, the API response depends on your conflicting [account management settings](https://knowledge.workspace.google.com/admin/users/find-and-add-unmanaged-users#set_option): * `201 Created`: Returned if no settings are configured, or the option is set to **Replace their conflicting account with managed one**. * `202 Accepted`: Returned if the option is set to **Automatic[...]",
                  "flatPath": "v1/customers/{customerId}/v2/Users",
                  "httpMethod": "POST",
                  "id": "cloudidentityscim.customers.v2.Users.create",
                  "path": "v1/customers/{customerId}/v2/Users",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user"
                  ]
                },
                "delete": {
                  "description": "Deletes a User.",
                  "flatPath": "v1/customers/{customerId}/v2/Users/{userId}",
                  "httpMethod": "DELETE",
                  "id": "cloudidentityscim.customers.v2.Users.delete",
                  "path": "v1/customers/{customerId}/v2/Users/{userId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user"
                  ]
                },
                "get": {
                  "description": "Retrieves a User.",
                  "flatPath": "v1/customers/{customerId}/v2/Users/{userId}",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.Users.get",
                  "path": "v1/customers/{customerId}/v2/Users/{userId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user",
                    "https://www.googleapis.com/auth/admin.directory.user.readonly"
                  ]
                },
                "list": {
                  "description": "Retrieves a list of Users. * Requests must specify a filter. Requests without a `filter` parameter return a `tooMany` error. * The `filter` parameter only supports equality on `userName` (for example, `userName eq \"user@domain.com\"`). * Sub-string matches (`co`, `sw`, `ew`), logical operators (`and`, `or`), and complex value filters are not supported. * Pagination is not supported.",
                  "flatPath": "v1/customers/{customerId}/v2/Users",
                  "httpMethod": "GET",
                  "id": "cloudidentityscim.customers.v2.Users.list",
                  "path": "v1/customers/{customerId}/v2/Users",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user",
                    "https://www.googleapis.com/auth/admin.directory.user.readonly"
                  ]
                },
                "patch": {
                  "description": "Updates a User using SCIM patch semantics. * A maximum of **20** operations is supported per User patch request.",
                  "flatPath": "v1/customers/{customerId}/v2/Users/{userId}",
                  "httpMethod": "PATCH",
                  "id": "cloudidentityscim.customers.v2.Users.patch",
                  "path": "v1/customers/{customerId}/v2/Users/{userId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/admin.directory.user"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "retrieved_from": "https://cloudidentityscim.googleapis.com/$discovery/rest?version=v1&key=****",
  "rootUrl": "https://cloudidentityscim.googleapis.com/",
  "servicePath": "",
  "title": "Cloud Identity SCIM API",
  "version": "v1",
  "version_module": true
}
