{
  "version": "v2beta",
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://meet.mtls.googleapis.com/",
  "batchPath": "batch",
  "servicePath": "",
  "title": "Google Meet API",
  "canonicalName": "Meet",
  "protocol": "rest",
  "ownerName": "Google",
  "revision": "20250213",
  "documentationLink": "https://developers.google.com/meet/api",
  "kind": "discovery#restDescription",
  "baseUrl": "https://meet.googleapis.com/v2beta/",
  "basePath": "/meet/v2beta/",
  "description": "Create and manage meetings in Google Meet.",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://meet.googleapis.com/",
  "id": "meet:v2beta",
  "resources": {
    "conferenceRecords": {
      "methods": {
        "get": {
          "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}",
          "path": "v2beta/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets a conference record by conference ID.",
          "id": "meet.conferenceRecords.get"
        },
        "list": {
          "flatPath": "v2beta/conferenceRecords",
          "id": "meet.conferenceRecords.list",
          "description": "Lists the conference records. By default, ordered by start time and in descending order.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ],
          "path": "v2beta/conferenceRecords"
        }
      },
      "resources": {
        "transcripts": {
          "resources": {
            "entries": {
              "methods": {
                "get": {
                  "description": "Gets a `TranscriptEntry` resource by entry ID. Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when the Google Docs transcript file is modified after generation.",
                  "path": "v2beta/{+name}",
                  "id": "meet.conferenceRecords.transcripts.entries.get",
                  "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries/{entriesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ]
                },
                "list": {
                  "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ],
                  "id": "meet.conferenceRecords.transcripts.entries.list",
                  "path": "v2beta/{+parent}/entries",
                  "httpMethod": "GET",
                  "description": "Lists the structured transcript entries per transcript. By default, ordered by start time and in ascending order. Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when the Google Docs transcript file is modified after generation."
                }
              }
            }
          },
          "methods": {
            "list": {
              "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/transcripts",
              "path": "v2beta/{+parent}/transcripts",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "description": "Lists the set of transcripts from the conference record. By default, ordered by start time and in ascending order.",
              "id": "meet.conferenceRecords.transcripts.list"
            },
            "get": {
              "path": "v2beta/{+name}",
              "httpMethod": "GET",
              "description": "Gets a transcript by transcript ID.",
              "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "id": "meet.conferenceRecords.transcripts.get"
            }
          }
        },
        "participants": {
          "resources": {
            "participantSessions": {
              "methods": {
                "get": {
                  "description": "Gets a participant session by participant session ID.",
                  "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions/{participantSessionsId}",
                  "id": "meet.conferenceRecords.participants.participantSessions.get",
                  "path": "v2beta/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ],
                  "path": "v2beta/{+parent}/participantSessions",
                  "description": "Lists the participant sessions of a participant in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted this API defaults to `'participantsessions/*, next_page_token'`.",
                  "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions",
                  "id": "meet.conferenceRecords.participants.participantSessions.list"
                }
              }
            }
          },
          "methods": {
            "get": {
              "description": "Gets a participant by participant ID.",
              "httpMethod": "GET",
              "path": "v2beta/{+name}",
              "id": "meet.conferenceRecords.participants.get",
              "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            },
            "list": {
              "id": "meet.conferenceRecords.participants.list",
              "path": "v2beta/{+parent}/participants",
              "description": "Lists the participants in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted, this API defaults to `'participants/*, next_page_token'`.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/participants"
            }
          }
        },
        "recordings": {
          "methods": {
            "get": {
              "path": "v2beta/{+name}",
              "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/recordings/{recordingsId}",
              "id": "meet.conferenceRecords.recordings.get",
              "description": "Gets a recording by recording ID.",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "description": "Lists the recording resources from the conference record. By default, ordered by start time and in ascending order.",
              "path": "v2beta/{+parent}/recordings",
              "id": "meet.conferenceRecords.recordings.list",
              "flatPath": "v2beta/conferenceRecords/{conferenceRecordsId}/recordings",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            }
          }
        }
      }
    },
    "spaces": {
      "methods": {
        "create": {
          "description": "Creates a space.",
          "httpMethod": "POST",
          "path": "v2beta/spaces",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created"
          ],
          "id": "meet.spaces.create",
          "flatPath": "v2beta/spaces"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly",
            "https://www.googleapis.com/auth/meetings.space.settings"
          ],
          "id": "meet.spaces.get",
          "httpMethod": "GET",
          "path": "v2beta/{+name}",
          "description": "Gets details about a meeting space. For an example, see [Get a meeting space](https://developers.google.com/meet/api/guides/meeting-spaces#get-meeting-space).",
          "flatPath": "v2beta/spaces/{spacesId}"
        },
        "endActiveConference": {
          "description": "Ends an active conference (if there's one). For an example, see [End active conference](https://developers.google.com/meet/api/guides/meeting-spaces#end-active-conference).",
          "flatPath": "v2beta/spaces/{spacesId}:endActiveConference",
          "id": "meet.spaces.endActiveConference",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created"
          ],
          "path": "v2beta/{+name}:endActiveConference"
        },
        "patch": {
          "path": "v2beta/{+name}",
          "description": "Updates details about a meeting space. For an example, see [Update a meeting space](https://developers.google.com/meet/api/guides/meeting-spaces#update-meeting-space).",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.settings"
          ],
          "id": "meet.spaces.patch",
          "flatPath": "v2beta/spaces/{spacesId}"
        }
      }
    }
  },
  "version_module": true,
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/meetings.space.readonly": {
          "description": "Read information about any of your Google Meet conferences"
        },
        "https://www.googleapis.com/auth/meetings.space.created": {
          "description": "Create, edit, and see information about your Google Meet conferences created by the app."
        },
        "https://www.googleapis.com/auth/meetings.space.settings": {
          "description": "Edit, and see settings for all of your Google Meet calls."
        }
      }
    }
  },
  "name": "meet",
  "basePath": ""
}
