name: Check for outdated GitHub Actions
on:
  schedule:
    - cron: '37 20 * * 3'
  workflow_dispatch:

jobs:
  check-actions:
    name: Check for GHA updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run actions-up
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx actions-up

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6 # Use the action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated changes"
          title: "GitHub Actions versions neeeding updating"
          body: "This PR was created automatically by a GitHub Action."
          branch: "automated-pr-branch"
