name: Push wiki
permissions:
  contents: write
on:
  push:
    paths:
      - 'wiki/**'
jobs:
  pushwiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GAM source
        run: |
          # checkout via normal shell here
          # so we're not authorized to actually make any changes
          git clone https://github.com/GAM-team/GAM

      - name: Checkout Wiki source
        uses: actions/checkout@master
        with:
          path: GAM.wiki
          repository: GAM-team/GAM.wiki
          persist-credentials: true
          fetch-depth: 0

      - name: Overwrite all Wiki repo files with /wiki from main git
        run: |
          # remove all wiki repo files so deletes work
          rm -fv GAM.wiki/*.md
          # copy all files from main GAM repo wiki folder
          cp -fv GAM/wiki/*.md GAM.wiki/

      - name: Commit Wiki changes
        run: |
          cd GAM.wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.md
          git commit -m "[no ci] Push Wiki changes"
          git status
          git push
